server:
  port: 8899

logging:
  level:
   com.netflix.discovery: 'OFF'
   org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/blue-blaze/spring-cloud-learning.git
          search-paths: conf-repo
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
    virtual-host: /
encrypt:
  key-store:
    alias: confserver
    password: confserver
    location: classpath:keystore.jks
    secret: confserver